jobs:
  validate_test:
    image: ubuntu
    requires: [~pr, ~commit]
    # Steps definition block.
    steps:
      - begin: echo begin
      - update: apt-get -y update
      - install_python: apt-get install -y python3 python3-dev python3-venv python3-pip
      - install_tox: python3 -m pip install tox
      - run_tox: |
          cd package
          tox
          cd ..
      - end: echo end
      # - set-metadata: meta set example.coverage 99.95
 